Add job support
Esri/arcgis-rest-js pull request #1020
Opened 2022-09-15 19:41 UTC by patrickarlt

Enhancement of https://github.com/Esri/arcgis-rest-js/pull/1018 with additional doc and minor fixes.

2022-09-20 17:46 UTC, patrickarlt commented on packages/arcgis-rest-request/src/job.ts
> +  getJobInfo() {
@marcysilverman it would be nice to build an interface (`IJobInfo`) that represents the response of the job info status call that includes all its properties.

```suggestion
  getJobInfo() : Promise<IJobInfo> {
```

2022-09-20 17:46 UTC, patrickarlt commented on packages/arcgis-rest-request/src/job.ts
> +   * @returns An object with the job id, job status, and messages array with a status property of type and description.
This doesn't return anything.

```suggestion
```

2022-09-20 17:47 UTC, patrickarlt commented on packages/arcgis-rest-request/src/job.ts
> +  on(eventName: string, handler: (e: any) => void) {
Once you build the `IJobInfo` interface we can use it here instead of `any`

```suggestion
  on(eventName: string, handler: (e: IJobInfo) => void) {
```

2022-09-20 17:48 UTC, patrickarlt commented on packages/arcgis-rest-request/src/job.ts
> +   * @returns An object as a JSON.
```suggestion
   * @returns The `Job` as a plain JavaScript object.
```

2022-09-20 17:48 UTC, patrickarlt commented on packages/arcgis-rest-request/src/job.ts
> +   * @returns A string.
```suggestion
   * @returns A JSON string representing the `Job`.
```

2022-09-20 17:49 UTC, patrickarlt commented on packages/arcgis-rest-request/src/job.ts
> +   * Converts JSON to a single string.
```suggestion
   * Converts the `Job` to a JSON string. You can rehydrate the state of the `Job` with {@linkcode Job.deserialize}.
```

2022-09-20 17:49 UTC, patrickarlt commented on packages/arcgis-rest-request/src/job.ts
> +   * @returns
This returns need to indicate this resolves or rejects with the job info.

2022-09-20 17:50 UTC, patrickarlt commented on packages/arcgis-rest-request/src/job.ts
> +  async waitForJobCompletion() {
Another good place for the `IJobInfo` interface once it gets filled out.

```suggestion
  async waitForJobCompletion() : Promise<IJobInfo> {
```

2022-09-22 04:02 UTC, gavinr requested changes
Overall looks great and I'm excited for this addition to ArcGIS REST JS. A few comments and suggestions:

2022-09-22 04:02 UTC, gavinr commented on demos/job/readme.md
> +# Job Class Demo
I attempted to run the job demo but got this error:

```
> job@1.0.0 start
> ts-node index.ts

file:///.../arcgis-rest-js/packages/arcgis-rest-request/src/request.ts:182
    throw new ArcGISRequestError(message, errorCode, response, url, options);
          ^
ArcGISRequestError: 403: User does not have permissions to access 'world/vehicleroutingproblem.gpserver'.
    at checkForErrors (file:///.../arcgis-rest-js/packages/arcgis-rest-request/src/request.ts:182:11)
    at file:///.../arcgis-rest-js/packages/arcgis-rest-request/src/request.ts:445:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: "User does not have permissions to access 'world/vehicleroutingproblem.gpserver'.",
  code: 403,
  response: {
    error: {
      code: 403,
      subcode: 2,
      message: "User does not have permissions to access 'world/vehicleroutingproblem.gpserver'.",
      details: []
    }
  },
  url: 'https://logistics.arcgis.com/arcgis/rest/services/World/VehicleRoutingProblem/GPServer/SolveVehicleRoutingProblem/submitJob',
  options: {
    httpMethod: 'POST',
    params: {
      f: 'json',
      orders: [Object],
      depots: [Object],
      routes: [Object],
      time_units: 'Minutes',
      distance_units: 'Miles',
      travel_mode: [Object],
      populate_directions: true,
      directions_language: 'en',
      populate_route_lines: false,
      default_date: '1608051600000'
    },
    authentication: '****',
    headers: {}
  }
}
npm ERR! Lifecycle script `start` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: job@1.0.0 
npm ERR!   at location: /.../arcgis-rest-js/demos/job
```

I assume this is because I'm using an API key from an organizational account ... is that correct? Perhaps we should explain what type of account is required for this demo, or can we change the demo to use a public GP service from sampleserver6 or something?

2022-09-22 15:36 UTC, marcysilverman commented
@gavinr, The demo at the top of the file, you'll see that is parsing SECRET_KEY. However it needs to match whatever property you've called it, we must have missed it there it should read like:

`const API_KEY = dotenv.config().parsed?.API_KEY;`

2022-09-23 16:35 UTC, patrickarlt commented
This is ready. @marcysilverman and I are having a meeting later today to debug some odd behavior we are seeing on sampleserver6.

2022-09-23 21:06 UTC, gavinr commented
Now when I run `npm start` in `demos/job`, it opens a browser but I don't see anything about jobs. Am I supposed to see a Job being run here?
![image](https://user-images.githubusercontent.com/209355/192056717-04dc52da-9c2a-49ca-a9b9-0ba10c1be847.png)

2022-09-26 18:44 UTC, marcysilverman approved these changes
LGTM!

2022-09-26 21:40 UTC, patrickarlt commented
@gavinr want to take a look again?

2022-09-27 04:02 UTC, gavinr approved these changes
I ran the demo - works for me now.

2022-09-28 19:32 UTC, merged