Developer Credential Package Initial Phase
Esri/arcgis-rest-js pull request #1111
Opened 2023-07-05 16:11 UTC by yida-tong

Please review: 

1. API Key Management logic. (Retrieve, Create, Update)
2. App Management logic. (Retrieve, Create)
3. Documentation contents.

Test cases are fully covered. If I miss some test aspects, let me know too.

2023-07-11 00:59 UTC, noahmulfinger requested changes
This is looking great, I just had a bunch of small-ish comments

2023-07-11 00:59 UTC, noahmulfinger commented on packages/arcgis-rest-developer-credentials/src/shared/helpers.ts
> +export const paramsEncodingToJsonStr = (requestOptions: IRequestOptions) => {
I think it's better to change the name of this function to `stringifyArrays` or similar. And the TODO can be removed.

2023-07-11 00:59 UTC, noahmulfinger commented on packages/arcgis-rest-developer-credentials/src/shared/registerApp.ts
> +    throw new Error("Contain invalid privileges");
Wording suggestion:
```suggestion
    throw new Error("The `privileges` option contains invalid privileges.");
```

2023-07-11 00:59 UTC, noahmulfinger commented on packages/arcgis-rest-developer-credentials/src/updateApiKey.ts
> +    throw new Error("Contain invalid privileges");
```suggestion
    throw new Error("The `privileges` option contains invalid privileges.");
```

2023-07-11 00:59 UTC, noahmulfinger commented on packages/arcgis-rest-developer-credentials/src/updateApiKey.ts
> +    throw new Error("App type is not api key.");
Wording suggestion:
```suggestion
  if (appResponse.appType !== "apikey" || !("apiKey" in appResponse)) {
    throw new Error("Item is not an API key.");
  }
```

2023-07-11 00:59 UTC, noahmulfinger commented on packages/arcgis-rest-developer-credentials/test/createApiKey.test.ts
> +  // let authEmptyToken: ArcGISIdentityManager;
```suggestion
```

2023-07-11 00:59 UTC, noahmulfinger commented on packages/arcgis-rest-developer-credentials/test/createApiKey.test.ts
> +  // it("should throw err if auth token is missing", async function () {
Removable comments

2023-07-11 00:59 UTC, noahmulfinger commented on demos/dev-credentials-client/demo.ts
Is this `demo.ts` file needed? I don't see it used anywhere

2023-07-12 18:03 UTC, yida-tong commented on packages/arcgis-rest-developer-credentials/test/updateApiKey.test.ts
> +    "AAPK27f2b7b36acd49778e872bb59fdc6137WeIxBAmg3WKOEIoeUPhuVDRyyBXxKCIaOHn7Dl2zhkMvy0mBndPvk0BSWRsxhnHb"
These "fake response" used to be real for convenience. I've deleted them.

2023-07-12 18:19 UTC, yida-tong commented on demos/dev-credentials-client/demo.ts
Pat demonstrated me how to write scripts by creating this file temporarily. Will remove it.

2023-07-12 19:12 UTC, yida-tong commented
@noahmulfinger thanks for your review! Changes have been made.

2023-07-13 00:10 UTC, noahmulfinger requested changes
A few more follow-up comments. 
- Since the app.js file is getting created when running the demo, let's ignore it by adding a file `demos/dev-credentials-client/.gitignore` with content:
   ```
   app.js
   ```

2023-07-13 00:10 UTC, noahmulfinger commented on demos/dev-credentials-client/app.ts
> +          const title = titleElement.value;
Would be good to add a check that the title field isn't empty before making the API call.

2023-07-13 14:36 UTC, gr-maps requested changes
Thanks for the hard work on this new package!

1. Within `demos/dev-credentials-client`, please add a `README.md` explaining what the demo does and how to use it (for an example of this, see the other demo folders, like `demos\jsapi-integration\README.md`)
2. I'm having an issue running the demo - when I run `npm start`, The browser opens and asks for my oauth arcgis username/password. I put that in and I get this:
![image](https://github.com/Esri/arcgis-rest-js/assets/137905994/dde79e98-b276-454e-923b-3a31a33dc4f2)
3. An overall comment for `demos/dev-credentials-client` - I would prefer a more basic version that demonstrates the functionality without adding too much extra libraries making it look good. It's ok if it does not look amazing as long as it shows how to use the new package. For example, in `demos\dev-credentials-client\apikeyManagement.html` removing bootstrap, jquery, and select2 and just using the native browser functionality (fetch and `<select>`) instead. This is just a preference though, happy to get input from others like @noahmulfinger and @patrickarlt  ... perhaps a compromise would be to keep the current demo and also add an additional demo, `demos/dev-credentials-simple` that has a much simpler demonstration case?

2023-07-13 17:36 UTC, yida-tong commented
@gr-maps thanks for your inputs! For your second point, have you run `npm run build` at root level. Seem like missing `@esri/arcgis-rest-developer-credentials/` in node_modules folder. Please let me know feedback.

2023-07-13 18:18 UTC, yida-tong commented on demos/dev-credentials-client/app.ts
> +  if (tokenRemainingTime <= 0) clearSession();
Will search all this issue in the package and fix them.

2023-07-13 18:46 UTC, yida-tong commented on demos/dev-credentials-client/app.ts
> +      const privilegesSelectOptions = usr.privileges!;
Got it. Should refer to Privileges enum as select options.

2023-07-13 21:49 UTC, yida-tong commented on demos/dev-credentials-client/app.ts
> +          const title = titleElement.value;
Good catch! I just notice both "title" and "type" are required in `IItemAdd`

Can add "required" attribute at HTML input.

2023-07-19 01:15 UTC, patrickarlt requested changes
@yida-tong. Overall this looks good. I made some specific comments which you can address.

The main issue now is the Node JS tests don't work (`npm run test:node`). There are 2 comments to address this which involve making sure the imports work in both Node and browser tests.

2023-07-19 01:15 UTC, patrickarlt commented on packages/arcgis-rest-developer-credentials/test/getApiKey.test.ts
> +import { TOMORROW } from "../../../scripts/test-helpers";
This needs to be fixed but there are other Node test errors that I'll comment on.

```suggestion
import { TOMORROW } from "../../../scripts/test-helpers.js";
```

2023-07-19 01:15 UTC, patrickarlt commented on packages/arcgis-rest-developer-credentials/test/getApiKey.test.ts
> +import { getApiKey, IRegisteredAppResponse, IApiKeyResponse } from "../src";
The Node tests also don't like importing from directories. You'll need to import directly from the exact files and have a `.js` extension to get this to work in Node. You can see some of the other tests for details.

2023-07-19 23:58 UTC, patrickarlt commented on packages/arcgis-rest-developer-credentials/src/shared/enum/PRIVILEGE.ts
> +  "portal:apikey:basemaps" = "portal:apikey:basemaps",
@yida-tong after some consultation with the other rest contributors we have decided that this should be PascalCase to match the other typescript enums. So:

* `portal:apikey:basemaps` > `Basemaps`
* `premium:user:networkanalysis:optimizedrouting` > `OptimizedRouting`

2023-07-20 21:26 UTC, yida-tong commented
@patrickarlt OAuth app task done. 

Branch coverage can't reach to 100% even though all test cases are carefully designed.

![Screenshot at Jul 20 13-54-10](https://github.com/Esri/arcgis-rest-js/assets/47749490/7d24c9c5-68de-4c66-b7fb-30e26cba4b4e)

2023-07-24 18:29 UTC, patrickarlt commented on packages/arcgis-rest-developer-credentials/src/createApiKey.ts
> +    httpReferrers: requestOptions?.httpReferrers || [],
Looking at this again this can actually be:

```suggestion
    httpReferrers: requestOptions.httpReferrers || [],
```

2023-07-27 18:53 UTC, noahmulfinger reviewed
Some more comments, mostly suggestions for the demo

2023-07-27 18:53 UTC, noahmulfinger commented on demos/dev-credentials-client/README.md
> +Next, you will use the form create an API key, which will be stored in RAM for simplicity purpose.
```suggestion
Then you can use the form to create an API key or switch to the OAuth 2.0 form to create an OAuth 2.0 app.
```

2023-07-27 18:53 UTC, noahmulfinger commented on demos/dev-credentials-client/README.md
> +To retrieve or update, please click a specific key in the table and continue your operation. If the named token is
Once you've created an API key or OAuth 2.0 app, you can click on the item in the table below the form to edit it.

2023-07-27 18:53 UTC, noahmulfinger commented on demos/dev-credentials-client/README.md
> +2. Run `npm start` to spin up the development server.
```suggestion
2. Go into `demos/dev-credentials-client` and run `npm start` to spin up the development server.
```

2023-07-27 18:53 UTC, noahmulfinger commented on demos/dev-credentials-client/README.md
> +## Credits
```suggestion
## Additional tools used
```

2023-07-27 18:53 UTC, noahmulfinger commented on demos/dev-credentials-client/app.ts
> +    pageTitleElement.innerHTML = `APIKey Management (sign in as: ${session.username})`;
```suggestion
    pageTitleElement.innerHTML = `APIKey Management (signed in as: ${session.username})`;
```

2023-07-27 18:53 UTC, noahmulfinger commented on demos/dev-credentials-client/index.html
> +    ArcGISIdentityManager.beginOAuth2({
I would recommend adjusting this page so that
- if the user is already signed in (stored in localStorage) it sends them to the `apikeyManagement.html` page. 
- if not signed in, it shows a sign in button that the user has to click to begin OAuth 2.0.

2023-07-27 18:53 UTC, noahmulfinger commented on demos/dev-credentials-client/oAuthAppIndex.html
Is this index page needed? I don't see it used in the demo.

2023-07-27 18:53 UTC, noahmulfinger commented on packages/arcgis-rest-developer-credentials/src/shared/enum/PRIVILEGE.ts
Maybe @patrickarlt can weigh in on this, but I feel like we should just name the file `privileges.ts`. We don't have any other all-caps file names.

2023-07-27 18:53 UTC, noahmulfinger commented on packages/arcgis-rest-developer-credentials/src/createOAuthApp.ts
> +    ...baseRequestOptions,
Is it possible for someone to manually pass in `httpReferrers` or `privileges` here by including them in the request options? Because we probably shouldn't let users do that since they aren't relevant to OAuth apps.

2023-07-27 18:53 UTC, noahmulfinger commented on packages/arcgis-rest-developer-credentials/test/getApiKey.test.ts
> +  it("should auto generateToken if auth token is invalid", async function () {
Just curious, does this need to be tested in this package? Seems like it's an internal part of the `request` function.

2023-07-27 18:53 UTC, noahmulfinger commented on demos/dev-credentials-client/apikeyManagement.html
> +                </a>
I would put this navigation button up above the form since it's unrelated to the form. Same applies to the other button on OAuth management form.

2023-07-27 18:53 UTC, noahmulfinger commented on demos/dev-credentials-client/apikeyManagement.html
> +                    <th>Modified</th>
I think it would look a little better if the table just listed the `title` and `itemId` properties. All the other properties can just be viewed in the `Details` section. And it would prevent the table from being too wide.

2023-07-28 15:10 UTC, patrickarlt commented on packages/arcgis-rest-developer-credentials/src/shared/enum/PRIVILEGE.ts
@yida-tong I agree lets rename this.

2023-07-28 17:10 UTC, yida-tong commented on packages/arcgis-rest-developer-credentials/src/createOAuthApp.ts
> +    ...baseRequestOptions,
Hi Noah, your highlight codes are request options for registerApp(), which allows user to feed `httpReferrers ` and `privileges`. Because registerApp() is used inside createOAuthApp(), line 94 and 95 is manually setting these fields to empty. 

As long as we call registerApp() properly, we shouldn't worry about it. Let me know if I hit the nail on the head in explanation.

2023-07-28 17:13 UTC, noahmulfinger commented on packages/arcgis-rest-developer-credentials/src/createOAuthApp.ts
> +    ...baseRequestOptions,
But can `baseRequestOptions` include `httpReferrers` or `privileges` provided by the user? Because then they would override the empty values.

2023-07-28 17:14 UTC, yida-tong commented on packages/arcgis-rest-developer-credentials/test/getApiKey.test.ts
> +  it("should auto generateToken if auth token is invalid", async function () {
Hi Noah, I was in test scripts study phase when I wrote this script. I didn't get everything completely at the beginning. As you can see, in newer test scripts related with oAuth 2 assignment, I skipped those unnecessary test. 

Leaving it there doesn't hurt. I am also okay to remove it. Let me know your inputs.

2023-07-28 17:24 UTC, patrickarlt requested changes
@yida-tong just 1 minor change. Please also address the changes from @noahmulfinger before we merge this.

2023-07-28 17:24 UTC, patrickarlt commented on packages/arcgis-rest-developer-credentials/src/getOAuthAppInfo.ts
> +export async function getOAuthAppInfo(
@yida-tong I think this should change to `getOAuthApp` to match `getApiKey` or `getApiKey` should change to `getApiKeyInfo` but I think i prefer `getOAuthApp` here. 

```suggestion
export async function getOAuthApp(
```

2023-07-28 17:37 UTC, yida-tong commented on packages/arcgis-rest-developer-credentials/src/createOAuthApp.ts
> +    ...baseRequestOptions,
For convenience, I paste extractBaseRequestOptions here. As you can see, `baseRequestOptions` excludes `httpReferrers` and `privileges`.


`
export function extractBaseRequestOptions<T extends IRequestOptions>(
  options: T
): Partial<IRequestOptions> {
  const requestOptionsProperties: Array<keyof T> = [
    "credentials",
    "headers",
    "hideToken",
    "httpMethod",
    "maxUrlLength",
    "portal",
    "rawResponse",
    "signal",
    "suppressWarnings"
  ];

  return filterKeys(options, requestOptionsProperties);
}
`

2023-07-28 17:52 UTC, noahmulfinger commented on packages/arcgis-rest-developer-credentials/src/createOAuthApp.ts
> +    ...baseRequestOptions,
Okay sounds good!

2023-07-28 20:13 UTC, merged