Allow arcgis rest places package to use dev endpoints
Esri/arcgis-rest-js pull request #1170
Opened 2024-06-12 18:45 UTC by MonikaKanduri4525

Address: https://devtopia.esri.com/ArcGISDevelopers/core/issues/5239

- Added an endpoint param for places method in arcgis-rest-places package which allows to override the built in URL.
- Added test cases 

Pending:
comments for TypeDoc

2024-06-17 17:28 UTC, patrickarlt requested changes
@MonikaKanduri4525 this looks great could you reset the demo URL and work on the typedoc comments based on my example?

I'm also going to ask @gavinr to review this as another contributor.

2024-06-17 21:21 UTC, gavinr-maps requested changes
Overall looks good! In addition to Patrick's comments, just a few small things:

2024-06-17 21:21 UTC, gavinr-maps commented on packages/arcgis-rest-places/test/findPlacesNearPoint.test.ts
> +        "https://placesdev-api.arcgis.com/arcgis/rest/services/places-service/v1/places/near-point",
Similar to Patrick's comment above, I think all these example URLs in the test spec files should be changed to 
```suggestion
        "https://places-api.arcgis.com/arcgis/rest/services/places-service/v1/places/near-point",
```

2024-06-17 21:21 UTC, gavinr-maps commented on packages/arcgis-rest-places/test/findPlacesNearPoint.test.ts
> +    const response = await findPlacesNearPoint({
In these tests files, since we're not using the `response` variable, I think you can leave that off, like this:
```suggestion
    await findPlacesNearPoint({
```

2024-06-18 19:02 UTC, MonikaKanduri4525 commented
@patrickarlt @gavinr-maps - Thanks for the inputs, addressed the feedback here [161a784](https://github.com/Esri/arcgis-rest-js/pull/1170/commits/161a7840e01ba70436ba4245c5c11c53d6a3d362)

2024-06-18 22:37 UTC, patrickarlt approved these changes
LGTM I'll merge once tests pass.

2024-06-18 23:28 UTC, merged