FEAT: Add postMessage auth wrappers
Esri/arcgis-rest-js pull request #762
Opened 2020-09-15 17:04 UTC by dbouwman

Adds static and instance methods to UserSession to support `postMessage` based authentication.

Adds a Guide to docs re: how to work with this

Note: The message types and payloads have been reviewed in internal meetings

2020-09-20 21:30 UTC, dasa requested changes

2020-09-20 21:30 UTC, dasa commented on packages/arcgis-rest-auth/src/UserSession.ts
> +          return reject(new Error('Rejected authentication request.'));
Should it do anything here? The app may be getting other valid messages.

2020-09-20 21:30 UTC, dasa commented on docs/src/guides/embedded-apps.md
> +- `embed=iframe` - tells the app it's embedded in an iframe. This allows the app to make ui changes like hiding headers etc
This parameter isn't needed since the app can detect this using `window !== window.parent`.

2020-09-20 21:30 UTC, dasa commented on docs/src/guides/embedded-apps.md
> +- `parentOrigin=https://myapp.com` - this tells the app what 'origin' to expect messages from, and also to ignore other origins. **note** this should be uri encoded
```suggestion
- `parentOrigin=https://myapp.com` - this tells the app what 'origin' to expect messages from, what origin to post messages to, and also to ignore other origins. **note** this should be uri encoded
```

2020-09-25 18:46 UTC, dasa commented on docs/src/guides/embedded-apps.md
> +- `embed=iframe` - tells the app it's embedded in an iframe. This allows the app to make ui changes like hiding headers etc
If we want to keep this param as a kind of signal telling the app that it should use `postMessage`, we should probably name it to be less generic in case the app has its own `embed` parameter. Maybe "arcgis:auth:embed=true"?

2020-10-02 17:27 UTC, dbouwman commented on packages/arcgis-rest-auth/src/UserSession.ts
> +          return reject(new Error('Rejected authentication request.'));
@dasa good call. I'll just drop the else.

2020-10-02 17:30 UTC, dbouwman commented on docs/src/guides/embedded-apps.md
> +- `embed=iframe` - tells the app it's embedded in an iframe. This allows the app to make ui changes like hiding headers etc
@dasa I'll change it to your suggestion

2020-10-02 19:49 UTC, dbouwman commented on packages/arcgis-rest-auth/src/UserSession.ts
> +          return reject(new Error('Rejected authentication request.'));
actually - since we return a Promise, we have to either resolve or reject. I'm going to resolve(null) for now and we can change if/when we operationally hit an issue

2020-10-02 19:54 UTC, dasa commented on packages/arcgis-rest-auth/src/UserSession.ts
> +          return reject(new Error('Rejected authentication request.'));
Wouldn't that make is resolve too early? It should still resolve eventually when it get's the right message.

2020-10-05 14:55 UTC, dbouwman commented on packages/arcgis-rest-auth/src/UserSession.ts
> +          return reject(new Error('Rejected authentication request.'));
@dasa Nice catch! I added a test which fires two `message`, the first one from another origin (which we ignore) and the second, from the parent origin, which we process.

2020-10-08 20:04 UTC, dasa commented on docs/src/guides/embedded-apps.md
> +  if (embedStyle === 'iframe' && parentOrigin) {
Should be updated to use look for "arcgis-auth-embed=true"

2020-10-08 20:39 UTC, dbouwman commented on docs/src/guides/embedded-apps.md
> +  if (embedStyle === 'iframe' && parentOrigin) {
gah! thanks for the close reading!

2020-10-08 20:58 UTC, dasa approved these changes
Just one small suggestion and 👍🏻

2020-10-08 20:58 UTC, dasa commented on docs/src/guides/embedded-apps.md
> +  if (useEmbedAuth && parentOrigin) {
```suggestion
  if (useEmbedAuth === "true" && parentOrigin) {
```

2020-10-09 18:47 UTC, tomwayson reviewed
Great work @dbouwman - I think my main hope would be that we could use a single query param.

2020-10-09 18:47 UTC, tomwayson commented on docs/src/guides/embedded-apps.md
> +But, if the "Host" application is not public and the embedded application is not public, we then run into the question of how to pass authentication from the "Host" to the embedded application.
```suggestion
However, if the embedded application is not public and the user has already logged into the "Host" application, we then run into the question of how to pass authentication from the "Host" to the embedded application.
```

2020-10-09 18:47 UTC, tomwayson commented on docs/src/guides/embedded-apps.md
> +The application acting as the host, should use oAuth to authenticate the user, and *before* rendering the iframe with the embedded application it must call `session.enablePostMessageAuth(validOrigins
```suggestion
The application acting as the host, should use oAuth to authenticate the user, and *before* rendering the iframe with the embedded application it must call `session.enablePostMessageAuth(validOrigins)`. This sets up a listener that will process the requests from the embedded application(s).
```

2020-10-09 18:47 UTC, tomwayson commented on docs/src/guides/embedded-apps.md
> +- `parentOrigin=https://myapp.com` - this tells the app what 'origin' to expect messages from, what origin to post messages to, and also to ignore other origins. **note** this should be uri encoded
These should use consistent casing; both should use either camel or kebab. Also, should the be consistent about using an `arcgis` prefix?

@dasa, since they both appear to be required, can we instead get away w/ a single `arcgis-auth-origin=myapp.com`? If that's present assume `arcgis-auth-embed=true`?

2020-10-09 18:47 UTC, tomwayson commented on docs/src/guides/embedded-apps.md
> +#### 4 Parent App Transitions Away
It seems like transitioning away is a specific reason to clean up and we may want to make this section more generic like:

```suggestion
`### Clean up`
```

For example, if the host app has a sign out button, does this need to be called there?

2020-10-09 18:47 UTC, tomwayson commented on docs/src/guides/embedded-apps.md
> +#### 4 Parent App Transitions Away
hm... looks like from below that once the authentication has been successfully passed from the host to the embedded app that the listener is removed. I think we should mention that here, and call out the scenarios where you might need to do it manually. I still think the transition example can be made more generic, like, "If the host app is no longer going to render the iframe before the embedded app has a chance to request the authentication, then it should manually clean up the listener by calling:`

2020-10-09 18:47 UTC, tomwayson commented on packages/arcgis-rest-auth/src/UserSession.ts
> +    this.hostHandler = this.createPostMessageHandler(validChildOrigins);
should we name this `_hostHandler`?

2020-10-09 19:22 UTC, dasa commented on docs/src/guides/embedded-apps.md
> +- `parentOrigin=https://myapp.com` - this tells the app what 'origin' to expect messages from, what origin to post messages to, and also to ignore other origins. **note** this should be uri encoded
That sounds good to me 👍🏻

2020-10-13 17:14 UTC, dasa commented on docs/src/guides/embedded-apps.md
> +- `arcgis-auth-origin=https://myapp.com` - this tells the app what 'origin' to expect messages from, what origin to post messages to, and also to ignore other origins. **note** this should be uri enc
This sentence from the old param may be good to copy over too:

> tells the app it's embedded in an iframe and should request auth from the parent.

2020-10-13 17:16 UTC, dbouwman commented on docs/src/guides/embedded-apps.md
> +- `arcgis-auth-origin=https://myapp.com` - this tells the app what 'origin' to expect messages from, what origin to post messages to, and also to ignore other origins. **note** this should be uri enc
Cool - I'll address w/ Tom's "Clean Up" section comment in a moment...

2020-10-13 20:58 UTC, merged