feat(getJsonResource and scrubControlChars): add getJsonResource and …
Esri/arcgis-rest-js pull request #764
Opened 2020-09-18 20:55 UTC by drewctate

…scrubControlChars

AFFECTS PACKAGES:
@esri/arcgis-rest-portal

2020-09-18 21:26 UTC, tomwayson requested changes
Nice work, but I think it would be better if rather than `getJsonResource()` we should implement `getItemResource()` as I propose here: 

https://github.com/Esri/arcgis-rest-js/pull/701#issuecomment-691164727

If there's some reason that we need to call `scrubControlChars()` every time a JSON resource is fetched, I'm sure you could work that into the above.

2020-09-18 21:26 UTC, tomwayson commented on packages/arcgis-rest-portal/src/util/scrub-control-chars.ts
> + * Doesn't remove characters
```suggestion
 * Returns a new string with all control characters removed.
 *
 * Doesn't remove characters from input string.
```

2020-09-18 21:26 UTC, tomwayson commented on packages/arcgis-rest-portal/src/items/get.ts
> +    .then(text => JSON.parse(scrubControlChars(text)));
why is `scrubControlChars()` needed here?

2020-09-21 16:08 UTC, drewctate commented on packages/arcgis-rest-portal/src/items/get.ts
> +    .then(text => JSON.parse(scrubControlChars(text)));
JSON resources in the wild occasionally come back with unescaped control characters which breaks `res.json()`. Still trying to track down why/how those make it in there, but this is a backstop to make sure that we at least get the JSON back without control chars instead of a total failure. We think this is fine because control characters are usually added inadvertently by copy-pasting from MS word, etc.

2020-09-21 16:08 UTC, drewctate commented on packages/arcgis-rest-portal/src/items/get.ts
> +    .then(text => JSON.parse(scrubControlChars(text)));
cc: @dbouwman

2020-09-21 16:29 UTC, tomwayson commented on packages/arcgis-rest-portal/src/items/get.ts
> +    .then(text => JSON.parse(scrubControlChars(text)));
that's great, would be good to have that in comments

2020-09-21 19:51 UTC, drewctate commented
Not sure how to deal with the failing test. It's angry about `response.blob` in NodeJS. I know that newer versions of `node-fetch` include this support.

2020-09-21 20:24 UTC, tomwayson commented
You have to skip that test in node by checking for `window`.

2020-09-21 20:26 UTC, tomwayson commented
or, I guess if newer versions really do support blobs, then maybe install one of those as a dev dependency and explicitly pass that to this test.

2020-09-28 16:41 UTC, drewctate commented
> See how the other tests for request() handle blobs.

@tomwayson Are you talking about [this](https://github.com/Esri/arcgis-rest-js/blob/d75fe7c35f7ed2346171e60662021c759e8ceed1/packages/arcgis-rest-portal/test/items/get.test.ts#L86-L87)?

2020-09-28 16:58 UTC, tomwayson approved these changes
yep, that's what I was talking about

2020-09-28 16:59 UTC, merged