Automatically refresh session and try again with new token on invalid token errors
Esri/arcgis-rest-js pull request #953
Opened 2022-03-03 20:31 UTC by patrickarlt

This PR adds extra support for `Invalid token.` errors. When `request` encounters an invalid token it checks if:

1. The `authentication` option `canRefresh` and has `refreshSession`.
2. The error is `498: Invalid token.`

In this scenario we call `e.retry()` calling `refreshCredentials()` to exchange for a fresh token and retry the request with a new token. 

This should handle edge cases where the server thinks a token is invalid but ArcGIS REST JS thinks it is valid OR were ArcGIS REST JS doesn't have an expiration stored for the token.

In order to avoid edge cases where a server continuously responds with `Invalid token` (for example for a resource that a user doesn't have access too) we have an `internalRequest` function which this implements everything EXCEPT the automatic retry logic. `internalRequest` is what is used when we retry auth errors. The public  `request` function is just `internalRequest` with the retry logic.

2022-03-03 21:54 UTC, noahmulfinger requested changes
Makes sense to me. I just had a few small suggestions and typo fixes.

2022-03-03 21:54 UTC, noahmulfinger commented on packages/arcgis-rest-request/src/request.ts
> +  // query params are applied.
```suggestion
  // for errors in GET requests we want the URL passed to the error to be the URL before
  // query params are applied.
```

2022-03-03 21:54 UTC, noahmulfinger commented on packages/arcgis-rest-request/test/request.test.ts
> +    it("should throw throw an error is it also fails with the new token", () => {
```suggestion
    it("should throw an error if it also fails with the new token", () => {
```

2022-03-03 21:54 UTC, noahmulfinger commented on packages/arcgis-rest-request/src/request.ts
> +      }, 1);
Since the default is already `1`, do we need to explicitly pass `1` as the second argument here?

2022-03-03 21:54 UTC, noahmulfinger commented on packages/arcgis-rest-request/src/request.ts
> +      (requestOptions.authentication as any).refreshSession
Would make sense to add `canRefresh` and `refreshSession` as optional props to the IAuthenticationManager interface? So you wouldn't have to type these as `any` here

2022-03-03 21:54 UTC, noahmulfinger commented on packages/arcgis-rest-request/src/request.ts
> +        return (requestOptions.authentication as any).refreshSession();
I don't see the rename from `refreshSession` to `refreshCredentials` in this PR.

2022-03-09 16:22 UTC, patrickarlt commented
@noahmulfinger this should be ready for a re-review now.

2022-03-10 23:02 UTC, dbouwman approved these changes
Looks good to me! Glad we're getting all this in for the 4.x release

2022-03-10 23:12 UTC, merged